#! /usr/bin/env python
# encoding: utf-8

import sys

def build(bld):
	obj = bld.create_obj('cpp', 'program')
	obj.find_sources_in_dirs('.', excludes=['EditorLevelIO_win32.cpp', 'EditorLevelIO_gtk.cpp'])
	obj.uselib='SDL SDL_image'
	obj.uselib_local='tk4common'
	obj.target='tk4editor'

	if sys.platform == "win32":
		obj.source.append('EditorLevelIO_win32.cpp')
	else:
		obj.uselib+=' GTK'
		obj.source.append('EditorLevelIO_gtk.cpp')


